const ACTIONS = {
  LOGIN: 'LOGIN',
  EDIT: 'EDIT',
  GET_EXCHANGE_RATES: 'GET_EXCHANGE_RATES',
  MAP_CURRENCIES: 'MAP_CURRENCIES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
  UPDATE_TOTAL: 'UPDATE_TOTAL',
};

export default ACTIONS;
