const ACTIONS = {
  LOGIN: 'LOGIN',
  GET_EXCHANGE_RATES: 'GET_EXCHANGE_RATES',
  MAP_CURRENCIES: 'MAP_CURRENCIES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  UPDATE_EXPENSES: 'UPDATE_EXPENSES',
  DEFINE_EDITING: 'DEFINE_EDITING',
  SET_EXPENSE_TO_EDIT: 'SET_EXPENSE_TO_EDIT',
};

export default ACTIONS;
